[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
normal = { family = "RobotoMono Nerd Font" }
size=14.0

[window]
opacity=0.7
padding = { x = 5, y = 5 }

[terminal]
shell = "/usr/bin/fish"

[mouse]

hide_when_typing = true
